apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - image: busybox
    name: time-check
    resources: {}
    command:
    - "/bin/sh"
    - "-c"
    - "mkdir -p /opt/time && while true; do date; sleep $TIME_FREQ; done > /opt/time/time-check.log"
    env:
    - name: TIME_FREQ
      value: "5"
    volumeMounts:
    - name: logs
      mountPath: "/opt/time"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: logs
    hostPath:
      path: "/opt/time/"
      type: DirectoryOrCreate
